version: '25.0.2'


services:
  go-aircraft_fleet:
   container_name: go-aircraft_fleet
   image: go-aircraft-fleet:1.0.0
   build: .
   environment:
    DATABASE_URL: "host=kashin.db.elephantsql.com user=ozlhuaop password=1Qe_Ynt4M78CfoubRUyRjlDXPUssEyVW dbname=ozlhuaop port=5432 sslmode=disable"
    ports:
      - "3000:3000" 
    depends_on:
      - kashin.db.elephantsql.com
  kashin.db.elephantsql.com:
    container_name: kashin.db.elephantsql.com
    image: postgres:11.18
    environment:
      POSTGRES_PASSWORD: 1Qe_Ynt4M78CfoubRUyRjlDXP
      POSTGRES_USER: ozlhuaop
      POSTGRES_DB: ozlhuaop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/volumes/data



         
